version: '{branch}-{build}'
image: Visual Studio 2015
clone_folder: C:\projects\ocio
test: off
configuration:
    - Release
platform:
    - x64
branches:
    only:
        - appveyor
    
environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON: "C:\Python27"

install:
  - cinstall: python
  
  # Boost
  - set BOOST_ROOT=C:\Libraries\boost
  - dir %BOOST_ROOT%
  - set BOOST_LIBRARYDIR=C:\Libraries\boost\lib64-msvc-14.0
  - set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%BOOST_ROOT%
  
build_script:
  - echo Running cmake...
  - cd c:\projects\ocio
  - mkdir build
  - mkdir build\windows64
  - cd build\windows64
  - cmake -G "%CMAKE_PLATFORM%" -DCMAKE_LIBRARY_PATH=%CMAKE_LIBRARY_PATH% -DCMAKE_INCLUDE_PATH=%CMAKE_INCLUDE_PATH%  -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% -DVERBOSE=1 ../..
  - dir c:\projects\ocio
  - dir c:\projects\ocio\build
  - dir c:\projects\ocio\build\windows64
  - cmake --build . --config %CONFIGURATION%

matrix:
    fast_finish: true